#pragma once

namespace TSSM
{
enum class Event
{
};

static const char* s_event_names[] = {
    "Unknown",
    "Enable All",
    "Disable",
    "Visible All ",
    "Invisible All ",
    "EnterPlayer",
    "ExitPlayer",
    "TouchPlayer",
    "ControlOff",
    "ControlOn",
    "Reset",
    "Increment",
    "Decrement",
    "Open",
    "Close",
    "Toggle",
    "Teleport Player",
    "OutOfBounds",
    "Run",
    "Stop",
    "Expired",
    "Move",
    "Destroy",
    "Pause",
    "Play",
    "PlayOne",
    "PlayMaybe",
    "RoomStart",
    "Invalidate",
    "Tilt",
    "Untilt",
    "Arrive",
    "Mount",
    "Dismount",
    "Break",
    "Pickup",
    "Death",
    "Kill",
    "On",
    "Off",
    "Patrol On",
    "Patrol Off",
    "Wander On",
    "Wander Off",
    "Detect Player On",
    "Detect Player Off",
    "Chase Player On",
    "Chase Player Off",
    "Go To Sleep",
    "Wake Up Villain",
    "Respawn",
    "PlayerDeath",
    "GiveChance",
    "GiveShinyObjects",
    "GiveHealth",
    "ButtonPress",
    "ButtonUnpress",
    "ArriveHalfway",
    "Hit",
    "ButtonPressAction",
    "Evaluate",
    "True",
    "False",
    "PadPressX",
    "PadPressSquare",
    "PadPressO",
    "PadPressTriangle",
    "PadPressL1",
    "PadPressL2",
    "PadPressR1",
    "PadPressR2",
    "PadPressStart",
    "PadPressSelect",
    "PadPressUp",
    "PadPressDown",
    "PadPressRight",
    "PadPressLeft",
    "FontBackdropOn",
    "FontBackdropOff",
    "UI Select",
    "UI Unselect",
    "UI Focus On",
    "UI Focus Off",
    "Collision On",
    "Collision Off",
    "Collision+Visible On",
    "Collision+Visible Off",
    "Scene Prepare",
    "Scene Finish",
    "Room Prepare",
    "Room Finish",
    "LobMaster Shoot",
    "LobMaster Reset",
    "FallToDeath",
    "UI Focus On+Select",
    "UI Focus Off+Unselect",
    "Set Pad Config to Preset A",
    "Set Pad Config to Preset B",
    "Set Pad Config to Preset C",
    "Set Pad Config to Preset D",
    "Pad Vibrate On",
    "Pad Vibrate Off",
    "Mono Sound",
    "Stereo Sound",
    "Increase Master Volume",
    "Decrease Master Volume",
    "Increase Music Volume",
    "Decrease Music Volume",
    "Increase SFX Volume",
    "Decrease SFX Volume",
    "IntroState_Sony",
    "IntroState_Publisher",
    "IntroState_Developer",
    "IntroState_License",
    "IntroState_Count",
    "TitleState_Start",
    "TitleState_Attract",
    "TitleState_Count",
    "LoadState_SelectMemCard",
    "LoadState_SelectSlot",
    "LoadState_Loading",
    "LoadState_Count",
    "OptionsState_Options",
    "OptionsState_Count",
    "SaveState_SelectMemCard",
    "SaveState_SelectSlot",
    "SaveState_Saving",
    "SaveState_Count",
    "PauseState_Pause",
    "PauseState_Options",
    "PauseState_Count",
    "GameState_FirstTime",
    "GameState_Play",
    "GameState_LoseChance",
    "GameState_GameOver",
    "GameState_SceneSwitch",
    "GameState_Dead",
    "SetIntroState_Sony",
    "SetIntroState_Publisher",
    "SetIntroState_Developer",
    "SetIntroState_License",
    "SetIntroState_Count",
    "SetTitleState_Start",
    "SetTitleState_Attract",
    "SetTitleState_Count",
    "SetLoadState_SelectMemCard",
    "SetLoadState_SelectSlot",
    "SetLoadState_Loading",
    "SetLoadState_Count",
    "SetOptionsState_Options",
    "SetOptionsState_Count",
    "SetSaveState_SelectMemCard",
    "SetSaveState_SelectSlot",
    "SetSaveState_Saving",
    "SetSaveState_Count",
    "SetPauseState_Pause",
    "SetPauseState_Options",
    "SetPauseState_Count",
    "SetGameState_FirstTime",
    "SetGameState_Play",
    "SetGameState_LoseChance",
    "SetGameState_GameOver",
    "SetGameState_SceneSwitch",
    "SetGameState_Dead",
    "Digup",
    "GameState_Exit",
    "SetGameState_Exit",
    "LobMaster Shoot From Widget",
    "Back",
    "Cancel",
    "Retry",
    "Select Card",
    "Select Slot",
    "OK",
    "VilHurtBoss",
    "Attack",
    "AttackOn",
    "AttackOff",
    "Drop pickup",
    "UI Add Char",
    "UI Del Char",
    "UI String Empty",
    "UI String Full",
    "UI String Send As Cheat",
    "UI Set Max Chars",
    "UI Cheat OK",
    "UI Cheat Bad",
    "VilReport_StartingChase",
    "VilReport_StartingAttack",
    "VilReport_StartingRetreat",
    "Preload",
    "Done",
    "Arcto",
    "Digup Reaction",
    "Set Check Point",
    "AnimPlay",
    "AnimPlayLoop",
    "AnimStop",
    "AnimPause",
    "AnimResume",
    "AnimTogglePause",
    "AnimPlayRandom",
    "AnimPlayMaybe",
    "SetSpeed",
    "Accelerate",
    "MoveToTarget",
    "SwingerFollow",
    "Impact",
    "StartTimer",
    "FinishedTimer",
    "UI Reset",
    "SetScaleFactor",
    "EnterEntity",
    "ExitEntity",
    "ENTER FLAGGED - DO NOT USE",
    "EXIT FLAGGED - DO NOT USE",
    "Drivenby",
    "FollowTarget",
    "FaceTarget",
    "WatchTarget",
    "CarChangeLaneRight",
    "CarChangeLaneLeft",
    "CarStart",
    "CarSetSwerveMode",
    "IncreaseSpeed",
    "DecreaseSpeed",
    "StartMoving",
    "StopMoving",
    "Swoosh",
    "TurretDestroyed",
    "NPC Speak Stop",
    "StartRumbleEffect",
    "Navigate To",
    "NPC Speak Start",
    "NPC Alert",
    "NPC Patrol Delay",
    "NPC Scramble Action End",
    "VilFakeChaseOff",
    "BossMMPushButton",
    "VilReport_DecayComplete",
    "VilGuardWidget",
    "TextureAnimateOn",
    "TextureAnimateOff",
    "TextureAnimateToggle",
    "ColorEffectOn",
    "ColorEffectOff",
    "ColorEffectToggle",
    "SetTextureAnimGroup",
    "SetTextureAnimSpeed",
    "TextureAnimateStep",
    "Emit",
    "Emitted",
    "TranslucentOn",
    "TranslucentOff",
    "TranslucentToggle",
    "Zip Line Env Damage",
    "VilGangTalkOff",
    "Give PowerUp",
    "RaceTimerReset",
    "Fire Cruise Bubble",
    "Car Success Anim Play",
    "Car Failure Anim Play",
    "Disable Group Contents",
    "NPC Charge",
    "OccludeOn",
    "OccludeOff",
    "RaceTimerPause",
    "RaceTimerResume",
    "RaceTimerSetBestTime",
    "RaceTimerWarning1",
    "RaceTimerWarning2",
    "RaceTimerWarning3",
    "RingChallengeStart",
    "Car Stop",
    "RingChallengeRun",
    "RingChallengeReset",
    "RingChallengeSuccess",
    "RingChallengeFailed",
    "Formation Changed",
    "Charge Resume",
    "Charge Pause",
    "NPC Charge Stop",
    "NPC Charge Completed",
    "Formation Charge Start",
    "SituationPlayerSuccess",
    "SituationPlayerFailure",
    "Show Hud",
    "Hide Hud",
    "FADE OUT",
    "SetRain",
    "SetSnow",
    "Script No Op",
    "ScriptReset",
    "WaitForInput",
    "Play Movie",
    "CelebrationAnimPlay",
    "???",
    "MusicTrack Replace",
    "Forward",
    "Reverse",
    "RumbleTest ",
    "RumbleLight ",
    "RumbleMedium ",
    "RumbleHeavy ",
    "Screen Adjustment ON",
    "Screen Adjustment OFF",
    "Set as Skydome",
    "Connect_IOwnYou",
    "Duplotron_WaveBegin",
    "Duplotron_WaveComplete",
    "Duplotron_NPCBorn",
    "Duplotron_NPCKilled",
    "Duplotron_MaxNPCExpired",
    "Duplotron_Pause",
    "Duplotron_Resume",
    "Set as Goo",
    "NPCScript_ScriptBegin",
    "NPCScript_ScriptEnd",
    "NPCScript_ScriptReady",
    "NPCScript_Halt",
    "NPCScript_SetPos",
    "NPCScript_SetDir",
    "NPCScript_LookNormal",
    "NPCScript_LookAlert",
    "NPCScript_FaceWidget",
    "NPCScript_FaceWidgetDone",
    "NPCScript_GotoWidget",
    "NPCScript_GotoWidgetDone",
    "NPCScript_AttackWidget",
    "NPCScript_AttackWidgetDone",
    "NPCScript_FollowWidget",
    "NPCScript_PlayAnim",
    "NPCScript_PlayAnimDone",
    "NPCScript_LeadPlayer",
    "Set Text",
    "Start Conversation",
    "End Conversation",
    "Switch",
    "Add Text",
    "Clear Text",
    "Open Teleport Box",
    "Close Teleport Box",
    "On Signal 0",
    "On Signal 1",
    "On Signal 2",
    "On Signal 3",
    "On Signal 4",
    "On Signal 5",
    "On Signal 6",
    "On Signal 7",
    "On Signal 8",
    "On Signal 9",
    "Stop Wait",
    "On Conversation Start",
    "On Conversation End",
    "Hit Melee",
    "Hit Bubble Bounce",
    "Hit Bubble Bash",
    "Hit Bubble Bowl",
    "Hit Patrick Slam",
    "Hit By Throwable",
    "Paddle Hit Left",
    "Paddle Hit Right",
    "Initiate Task",
    "Set Success",
    "Set Failure",
    "On Accept",
    "On Decline",
    "On Complete",
    "Generate Boulder",
    "Launch Boulder At Widget",
    "Launch Boulder At Point",
    "Launch Boulder At Player",
    "Duplotron_SuperDuperDone",
    "Duplotron_DuperIsDoner",
    "Bus Switch Character",
    "Group Update Together",
    "Set Update Distance",
    "Translate, Local X",
    "Translate, Local Y",
    "Translate, Local Z",
    "Translate, World X",
    "Translate, World Y",
    "Translate, World Z",
    "Rotate, Local X",
    "Rotate, Local Y",
    "Rotate, Local Z",
    "Rotate, World X",
    "Rotate, World Y",
    "Rotate, World Z",
    "Translate, Local X Done",
    "Translate, Local Y Done",
    "Translate, Local Z Done",
    "Translate, World X Done",
    "Translate, World Y Done",
    "Translate, World Z Done",
    "Rotate, Local X Done",
    "Rotate, Local Y Done",
    "Rotate, Local Z Done",
    "Rotate, World X Done",
    "Rotate, World Y Done",
    "Rotate, World Z Done",
    "Count1",
    "Count2",
    "Count3",
    "Count4",
    "Count5",
    "Count6",
    "Count7",
    "Count8",
    "Count9",
    "Count10",
    "Count11",
    "Count12",
    "Count13",
    "Count14",
    "Count15",
    "Count16",
    "Count17",
    "Count18",
    "Count19",
    "Count20",
    "Set State",
    "Enter SpongeBob",
    "Enter Patrick",
    "Enter Sandy",
    "Exit SpongeBob",
    "Exit Patrick",
    "Exit Sandy",
    "NPCSpecial_PlatformSnap",
    "NPCSpecial_PlatformFall",
    "Goo set warb coeffs",
    "Goo set freeze duration",
    "Goo melt",
    "Set State Range",
    "Set State Delay",
    "Set Transition Delay",
    "NPC Fight On",
    "NPC Fight Off",
    "NPC Patrol Spline On",
    "NPC Patrol Spline Off",
    "NPC Kill Quietly",
    "Hit (General)",
    "Hit (Head)",
    "Hit (Left Arm)",
    "Hit (Right Arm)",
    "Hit (Left Leg)",
    "Hit (Right Leg)",
    "Hit (Lower Body)",
    "GiveSocks (current level)",
    "GiveCollectables (current level)",
    "SetSocks (current level)",
    "SetCollectables (current level)",
    "On Answer Yes",
    "On Answer No",
    "Hit Cruise Bubble",
    "Duplotron_KillKids",
    "On Signal10",
    "On Signal11",
    "On Signal12",
    "On Signal13",
    "On Signal14",
    "On Signal15",
    "On Signal16",
    "On Signal17",
    "On Signal18",
    "On Signal19",
    "Spongeball On",
    "Spongeball Off",
    "Launch Shrapnel",
    "NPC HP Incremented",
    "NPC HP Decremented",
    "NPC Set Active On",
    "NPC Set Active Off",
    "Switch Player Character",
    "Level Begin",
    "Scene Reset (death)",
    "Scene Enter",
    "Destroyed Tiki",
    "Destroyed Robot",
    "See Wood Tiki",
    "See Lovey Tiki",
    "See Shhh Tiki",
    "See Thunder Tiki",
    "See Stone Tiki",
    "See Fodder",
    "See Hammer",
    "See Tar-Tar",
    "See G-Love",
    "See Monsoon",
    "See Sleepy Time",
    "See Arf",
    "See Tubelets",
    "See Slick",
    "See King Jellyfish",
    "See Prawn",
    "See Dutchman",
    "See Sandy Boss",
    "See Patrick Boss",
    "See SpongeBob Boss",
    "See Robot Plankton",
    "Change Texture of UI",
    "NPC Cheer For Me",
    "Fast Visible",
    "Fast Invisible",
    "ZipLine Mount",
    "ZipLine Dismount",
    "Target",
    "Fire",
    "Camera FX Shake",
    "Bullet Time",
    "Thrown",
    "NPC Patrol",
    "EnterCruise",
    "ExitCruise",
    "CruiseFired",
    "CruiseDied",
    "CruiseAddLife",
    "CruiseSetLife",
    "CruiseResetLife",
    "Camera Collide Off",
    "Camera Collide On",
    "Slide On",
    "Slide Off",
    "Timer Set",
    "Timer Add",
    "NPC Force Conversation",
    "Make A Splash",
    "Credits start",
    "Credits stop",
    "Credits ended",
    "Bubble Wipe",
    "Set Lightkit",
    "Set Opacity",
    "Set Sound Effect",
    "Scale",
    "Set Reference",
    "Warp Set World",
    "Warp Set Task",
    "Warp Go",
    "Set Count",
    "Get Dash Speed",
    "Dash Trip",
    "Dash Burst",
    "Dash Fast",
    "Dash Normal",
    "Dash Slow",
    "Take Socks",
    "Debug BREAK",
    "Born",
    "Platform Pause",
    "Platform Unpause",
    "Store Options",
    "Restore Options",
    "UI Set Motion",
    "UI Motion Finished",
    "UI Motion Loop",
    "Destructible launch",
    "Destructible respawn",
    "Kaboom Start",
    "Kaboom Stop",
    "NPC Attack",
    "NPC Defend",
    "Train Set Speed",
    "Train Junct Out 1",
    "Train Junct Out 2",
    "Train Junct Toggle",
    "Train Junct Passed",
    "Train Car Detach",
    "Train Car Explode",
    "Xbox Initialize NET API",
    "Xbox Update Connection",
    "Xbox Update Online Task",
    "Xbox Update Account List",
    "Xbox Check for new content",
    "Xbox Select Device",
    "Xbox Select Content",
    "Xbox Verify Content",
    "Xbox Remove Content",
    "Xbox Select Device after remove",
    "Xbox Confirm use content idx",
    "Xbox Confirm no use content idx",
    "Xbox No content is installed",
    "Xbox No new content is available",
    "Xbox New content is available",
    "Enable Scene Drawing",
    "Disable Scene Drawing",
    "Lightning Start",
    "Lightning Stop",
    "Change Boss UI Stage",
    "Start static camera",
    "End static camera",
    "Set Camera Start Orientation",
    "NPC Set Movepoint Path",
    "NPC Scare Begin",
    "NPC Scare Skip",
    "NPC Set Movepoint Group",
    "VentSetStateIdle",
    "VentSetStateWarn",
    "VentSetStateDamage",
    "VentSetStateOff",
    "Waterhose Start",
    "Waterhose Stop",
    "Waterhose Set Length",
    "Carried",
    "Explode",
    "Jump To",
    "Jump on Spawn",
    "Player Hit",
    "Start Fade",
    "Fade Down Done",
    "Fade Up Done",
    "Bounce",
    "Launch NPC",
    "Upgrade Power Up",
    "Bullet Streak",
    "Set Follow Camera Orientation",
    "High Dynamic Range Fade",
    "Start",
    "Success",
    "Failure",
    "Enable Restore",
    "Disable Restore",
    "NPC Spawn",
    "NPC Spawn Done",
    "Spawned NPC Killed",
    "Spawned NPC No Health",
    "Spawned NPCs All Killed",
    "Spawned NPCs All No Health",
    "Set Dash Timer",
    "Dash Not Out of Time",
    "Dash Out of Time",
    "Force Scene Reset",
    "NPC Active",
    "NPC Inactive",
    "Duplicator Activate",
    "Duplicator Deactivate",
    "Dash Enter Tunnel",
    "Dash Exit Tunnel",
    "StopRumbleEffect",
    "Dash Chase Lasers On",
    "Dash Chase Lasers Off",
    "Random Jump on Spawn",
    "Hit Patrick Cartwheel",
    "UI Visible+Focus On+Select",
    "UI Focus Off+Unselect+Invisible",
    "Copy Reference",
    "UI Motion In Finished",
    "UI Motion Out Finished",
    "UI Signal Activate Screen",
    "UI Signal Deactivate Screen",
    "UI Signal Activated Screen",
    "UI Signal Switch Screens",
    "UI Signal Start Fade Out",
    "UI Signal Start Fade In",
    "UI Signal Screen Motion In Done",
    "UI Signal Screen Motion Out Done",
    "UI Signal Main Box In Done",
    "UI Signal Main Box Out Done",
    "UI Reset Motion",
    "UI Enable HDR",
    "UI Disable HDR",
    "UI Brighten",
    "UI Unbrighten",
    "UI Signal Deactivated Screen",
    "NPC Detect Always",
    "NPC Detect Never",
    "NPC Detect Normal",
    "NPC Fight Default",
    "Camera Collide Partial",
    "MusicTrack Play Temporary",
    "Evaluate Counter Value",
    "Count0",
    "Rotate to Absolute X",
    "Rotate to Absolute Y",
    "Rotate to Absolute Z",
    "Play Trigger Animation",
    "Triggered Animation Done",
    "UI Signal More",
    "UI Signal No More",
    "UI Signal Less",
    "UI Signal No Less",
    "UI Signal Up",
    "UI Signal Down",
    "UI Signal Sync To Current",
    "UI Signal Effect",
    "Freeze Player",
    "Unfreeze Player",
    "UI Signal Map Start",
    "UI Signal Map End",
    "Translate to Absolute X",
    "Translate to Absolute Y",
    "Translate to Absolute Z",
    "JSP Visibility Increment",
    "JSP Visibility Decrement",
    "Enter Camera",
    "Exit Camera",
    "PadPressE (GC Z or XBOX Black)",
    "Dash Set Jump Paramters",
    "Viper Face Player",
    "Viper Face Movement",
    "RequestStart",
    "UI Auto Menu Run",
    "UI Auto Menu Run Up",
    "UI Auto Menu Run Down",
    "UI Auto Menu Run Left",
    "UI Auto Menu Run Right",
    "Increment Success",
    "Decrement Success",
    "Increment Failed",
    "Decrement Failed",
    "MusicTrack Stop Temporary Music",
    "NPC Scramble Action Begin",
    "NPC Scramble Alert",
    "NPC Turret Set Attack Radius",
    "Goo Freeze Start",
    "Goo Melt Start",
    "NPC Notice",
    "Boss Stage Set",
    "Boss Stage Began",
    "Boss Stage Ended",
    "Boss Stage A Began",
    "Boss Stage A Ended",
    "Boss Stage B Began",
    "Boss Stage B Ended",
    "Boss Stage C Began",
    "Boss Stage C Ended",
    "Visibility Cull On",
    "Visibility Cull Off",
    "Start rband camera",
    "End rband camera",
    "Mindy Start",
    "Mindy End",
    "Flamethrower Start",
    "Flamethrower Stop",
    "Flamethrower Set Length",
    "NPC Take No Damage On",
    "NPC Take No Damage Off",
    "Start StaticCAM FOV filter",
    "Restore StaticCAM FOV",
    "XBOX DEMO exit to launcher",
    "Spawn",
    "Spawned",
    "Credits set dest",
    "Allow Attract Mode",
    "Disallow Attract Mode",
    "Rocket Attack",
    "Collision Reset",
    "AutoSave",
    "Open Bonus",
    "Flag Level",
    "Level End",
    "Get Local Content",
    "Pause Game Safe",
    "Override Frequency",
    "Reset Frequency",
    "Set Shot Delay",
    "Set Shots In Group",
    "User Select Yes",
    "User Select No",
    "User Select Back",
    "Launch Fire Works",
    "Resets user selection",
    "Set as Bounce Back",
    "Reset Unlockables",
    "UI Sys Msg Wait Response",
    "UI Sys Msg Wait Confirm",
    "UI Sys Msg Confirm",
    "UI Sys Msg Accept",
    "UI Sys Msg Decline",
    "Set as NOT Bounce Back",
    "Pause Game Now",
    "Patty Wagon Start Engine",
    "Patty Wagon Stop Engine",
    "Bubble Spawn On",
    "Bubble Spawn Off",
    "XBLive Toggle Sign In",
    "XBLive Manage Friends",
    "Apply On Reset - On",
    "Apply On Reset - Off",
    "Snap To",
    "Throw",
    "First Zip Line",
    "First Ledge Grab",
    "First Incredimeter Pickup",
    "UI Spark Trail",
    "UI Get Battle Scenes",
    "UI Battle Scenes Available",
    "UI Battle Scenes Not Available",
    "XBLive Toggle Appear Online",
    "UI Return to previous screen",
    "UI Empty Event",
    "Subtitles Enabled",
    "Subtitles Disabled",
    "UI Set Box Mapping for UVs",
    "Player Ejected",
    "Damage Player",
    "First Health Pickup",
    "Token Pickup Complete",
    "Prompt is dead",
    "UI Flip Visibility",
    "XBLive Reboot To Dashboard",
    "First Powerup Point",
};
}
